version: '3'

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    image: file-handler-benchmark
    container_name: file-handler-benchmark
    ports:
      - "7701:7701"
    volumes:
      - .:/app
    environment:
      - GS_PATH=/usr/bin/gs
      - PORT=7701
    restart: unless-stopped